<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="28">
            <File firstVisibleLine="8" xOffset="0" scrollWidth="896" startPos="2748" endPos="2748" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\gest\gestnotas\config\web.php" backupFilePath="" originalFileLastModifTimestamp="1431706818" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="392" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\aplicaciones\assets\AppAsset.php" backupFilePath="" originalFileLastModifTimestamp="1429072768" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="304" startPos="284" endPos="284" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\gestnotas\models\Users.php" backupFilePath="" originalFileLastModifTimestamp="1431869824" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="376" startPos="50" endPos="50" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\gestnotas\config\params.php" backupFilePath="" originalFileLastModifTimestamp="1431884036" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="800" startPos="254" endPos="254" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\models\User.php" backupFilePath="" originalFileLastModifTimestamp="1431872161" />
            <File firstVisibleLine="295" xOffset="0" scrollWidth="936" startPos="12142" endPos="12142" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\gest\gitlab\gestnotas\vendor\yiisoft\yii2\base\Application.php" backupFilePath="" originalFileLastModifTimestamp="1431917132" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="568" startPos="1195" endPos="1195" selMode="0" lang="Normal Text" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\composer.json" backupFilePath="" originalFileLastModifTimestamp="1431992515" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="536" startPos="176" endPos="176" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\config\db.php" backupFilePath="" originalFileLastModifTimestamp="1431872391" />
            <File firstVisibleLine="14" xOffset="0" scrollWidth="896" startPos="1124" endPos="1124" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\config\web.php" backupFilePath="" originalFileLastModifTimestamp="1431935350" />
            <File firstVisibleLine="36" xOffset="0" scrollWidth="1088" startPos="1541" endPos="1541" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\views\layouts\main.php" backupFilePath="" originalFileLastModifTimestamp="1431968866" />
            <File firstVisibleLine="34" xOffset="0" scrollWidth="984" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\views\layouts\main2.php" backupFilePath="" originalFileLastModifTimestamp="1431910820" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="600" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\controllers\EstudiantesController.php" backupFilePath="" originalFileLastModifTimestamp="1431872161" />
            <File firstVisibleLine="16" xOffset="0" scrollWidth="5088" startPos="3509" endPos="3509" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\views\site\about.php" backupFilePath="" originalFileLastModifTimestamp="1431939113" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1160" startPos="981" endPos="981" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\views\asignaturas\index.php" backupFilePath="" originalFileLastModifTimestamp="1431872199" />
            <File firstVisibleLine="13" xOffset="135" scrollWidth="1688" startPos="4478" endPos="4478" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\views\estudiantes\_form.php" backupFilePath="" originalFileLastModifTimestamp="1431976484" />
            <File firstVisibleLine="2003" xOffset="0" scrollWidth="824" startPos="75711" endPos="75711" selMode="0" lang="Normal Text" encoding="-1" filename="C:\xampp\php\php.ini" backupFilePath="" originalFileLastModifTimestamp="1433123812" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="800" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\models\FormUpload.php" backupFilePath="" originalFileLastModifTimestamp="1431994105" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1396" startPos="291" endPos="291" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\views\site\download.php" backupFilePath="" originalFileLastModifTimestamp="1431994616" />
            <File firstVisibleLine="79" xOffset="0" scrollWidth="856" startPos="2131" endPos="2131" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\controllers\SiteController.php" backupFilePath="" originalFileLastModifTimestamp="1431998404" />
            <File firstVisibleLine="11" xOffset="0" scrollWidth="1136" startPos="485" endPos="438" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\login\repoProfe\gestnotas\views\estudiantes\index.php" backupFilePath="" originalFileLastModifTimestamp="1431872199" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="664" startPos="294" endPos="303" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\practica\test\gestnotas\views\site\upload.php" backupFilePath="" originalFileLastModifTimestamp="1431989794" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1656" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\yii2-file-upload-widget-master\src\views\download.php" backupFilePath="" originalFileLastModifTimestamp="1431614044" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="584" startPos="1194" endPos="1194" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\moodle\install\lang\an\langconfig.php" backupFilePath="" originalFileLastModifTimestamp="1432847324" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="832" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\moodle\theme\flexibase\layout\includes\carousel2.php" backupFilePath="" originalFileLastModifTimestamp="1427074046" />
            <File firstVisibleLine="22" xOffset="0" scrollWidth="568" startPos="1747" endPos="1747" selMode="0" lang="CSS" encoding="-1" filename="C:\xampp\htdocs\moodle\theme\flexibase\style\carousel.css" backupFilePath="" originalFileLastModifTimestamp="1427074046" />
            <File firstVisibleLine="17" xOffset="0" scrollWidth="948" startPos="7241" endPos="7241" selMode="0" lang="CSS" encoding="-1" filename="C:\xampp\htdocs\moodle\theme\flexibase\style\coursebox.css" backupFilePath="" originalFileLastModifTimestamp="1427074046" />
            <File firstVisibleLine="88" xOffset="0" scrollWidth="896" startPos="5322" endPos="5322" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\moodle\theme\flexibase\settings\awesomebar.php" backupFilePath="" originalFileLastModifTimestamp="1427074046" />
            <File firstVisibleLine="129" xOffset="0" scrollWidth="920" startPos="5824" endPos="5824" selMode="0" lang="PHP" encoding="-1" filename="C:\xampp\htdocs\moodle\theme\flexibase\layout\frontpage.php" backupFilePath="" originalFileLastModifTimestamp="1427074046" />
            <File firstVisibleLine="207" xOffset="0" scrollWidth="1504" startPos="8926" endPos="8926" selMode="0" lang="HTML" encoding="-1" filename="C:\xampp\htdocs\wordpress\wp-content\themes\template\demo\index.html" backupFilePath="" originalFileLastModifTimestamp="1453525321">
                <Fold line="22" />
                <Fold line="30" />
            </File>
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
